ALPACA_SECRET_KEY = 'A2fPB2dWZuqRQLAOaa2YEZXxvrQaWJLd5AFOaxFq'
ALPACA_KEY = 'PKZN9T5IWKS6Y6HYPUZ9'

HEADERS = {
    'APCA-API-KEY-ID': ALPACA_KEY,
    'APCA-API-SECRET-KEY': ALPACA_SECRET_KEY
}

APCA_API_BASE_URL = 'https://paper-api.alpaca.markets'

OPENAI_API_KEY = 'sk-proj-nYVR2FE3qdiv01RExuRpT3BlbkFJyf9jdzymOZ3yqd2rpAqX'
