ALPACA_SECRET_KEY = 'Your ALPACA SECRET KEY'
ALPACA_KEY = 'Your ALPACA KEY'

HEADERS = {
    'APCA-API-KEY-ID': ALPACA_KEY,
    'APCA-API-SECRET-KEY': ALPACA_SECRET_KEY
}

APCA_API_BASE_URL = 'https://paper-api.alpaca.markets'

OPENAI_API_KEY = 'sk-proj-gKQGVpIJjG4jM1CbIWMET3BlbkFJ8iLWUnLVQipRH8yJimTg'